// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type IsActive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsUp bool `protobuf:"varint,1,opt,name=isUp,proto3" json:"isUp,omitempty"`
}

func (x *IsActive) Reset() {
	*x = IsActive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsActive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsActive) ProtoMessage() {}

func (x *IsActive) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsActive.ProtoReflect.Descriptor instead.
func (*IsActive) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *IsActive) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Timezone   string `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type MonitorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonitorData string `protobuf:"bytes,1,opt,name=monitorData,proto3" json:"monitorData,omitempty"`
}

func (x *MonitorData) Reset() {
	*x = MonitorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorData) ProtoMessage() {}

func (x *MonitorData) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorData.ProtoReflect.Descriptor instead.
func (*MonitorData) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *MonitorData) GetMonitorData() string {
	if x != nil {
		return x.MonitorData
	}
	return ""
}

type MonitorDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName     string `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	LogType        string `protobuf:"bytes,2,opt,name=logType,proto3" json:"logType,omitempty"`
	From           int64  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To             int64  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	Time           int64  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	IsCustomMetric bool   `protobuf:"varint,6,opt,name=isCustomMetric,proto3" json:"isCustomMetric,omitempty"`
}

func (x *MonitorDataRequest) Reset() {
	*x = MonitorDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorDataRequest) ProtoMessage() {}

func (x *MonitorDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorDataRequest.ProtoReflect.Descriptor instead.
func (*MonitorDataRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *MonitorDataRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *MonitorDataRequest) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *MonitorDataRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MonitorDataRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *MonitorDataRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *MonitorDataRequest) GetIsCustomMetric() bool {
	if x != nil {
		return x.IsCustomMetric
	}
	return false
}

var File_api_api_proto protoreflect.FileDescriptor

var file_api_api_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x1d, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x1e, 0x0a, 0x08, 0x49,
	0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x55, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x55, 0x70, 0x22, 0x48, 0x0a, 0x0a, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d,
	0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d,
	0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x22, 0x2f, 0x0a, 0x0b, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0xae, 0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x69, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x32, 0xce, 0x03, 0x0a, 0x12, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d,
	0x0a, 0x0a, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a,
	0x04, 0x49, 0x73, 0x55, 0x70, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x09, 0x49, 0x6e, 0x69, 0x74, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x11, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x17,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x18, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x1d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x15, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData = file_api_api_proto_rawDesc
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_proto_rawDescData)
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_api_proto_goTypes = []interface{}{
	(*Void)(nil),               // 0: api.Void
	(*Message)(nil),            // 1: api.Message
	(*IsActive)(nil),           // 2: api.IsActive
	(*ServerInfo)(nil),         // 3: api.ServerInfo
	(*MonitorData)(nil),        // 4: api.MonitorData
	(*MonitorDataRequest)(nil), // 5: api.MonitorDataRequest
}
var file_api_api_proto_depIdxs = []int32{
	3, // 0: api.MonitorDataService.HandlePing:input_type -> api.ServerInfo
	3, // 1: api.MonitorDataService.IsUp:input_type -> api.ServerInfo
	3, // 2: api.MonitorDataService.InitAgent:input_type -> api.ServerInfo
	4, // 3: api.MonitorDataService.HandleMonitorData:input_type -> api.MonitorData
	4, // 4: api.MonitorDataService.HandleCustomMonitorData:input_type -> api.MonitorData
	5, // 5: api.MonitorDataService.HandleMonitorDataRequest:input_type -> api.MonitorDataRequest
	3, // 6: api.MonitorDataService.HandleCustomMetricNameRequest:input_type -> api.ServerInfo
	0, // 7: api.MonitorDataService.HandleAgentIdsRequest:input_type -> api.Void
	1, // 8: api.MonitorDataService.HandlePing:output_type -> api.Message
	2, // 9: api.MonitorDataService.IsUp:output_type -> api.IsActive
	1, // 10: api.MonitorDataService.InitAgent:output_type -> api.Message
	1, // 11: api.MonitorDataService.HandleMonitorData:output_type -> api.Message
	1, // 12: api.MonitorDataService.HandleCustomMonitorData:output_type -> api.Message
	4, // 13: api.MonitorDataService.HandleMonitorDataRequest:output_type -> api.MonitorData
	1, // 14: api.MonitorDataService.HandleCustomMetricNameRequest:output_type -> api.Message
	1, // 15: api.MonitorDataService.HandleAgentIdsRequest:output_type -> api.Message
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsActive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_rawDesc = nil
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MonitorDataServiceClient is the client API for MonitorDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorDataServiceClient interface {
	HandlePing(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error)
	IsUp(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*IsActive, error)
	InitAgent(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error)
	HandleMonitorData(ctx context.Context, in *MonitorData, opts ...grpc.CallOption) (*Message, error)
	HandleCustomMonitorData(ctx context.Context, in *MonitorData, opts ...grpc.CallOption) (*Message, error)
	HandleMonitorDataRequest(ctx context.Context, in *MonitorDataRequest, opts ...grpc.CallOption) (*MonitorData, error)
	HandleCustomMetricNameRequest(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error)
	HandleAgentIdsRequest(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Message, error)
}

type monitorDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorDataServiceClient(cc grpc.ClientConnInterface) MonitorDataServiceClient {
	return &monitorDataServiceClient{cc}
}

func (c *monitorDataServiceClient) HandlePing(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.MonitorDataService/HandlePing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) IsUp(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*IsActive, error) {
	out := new(IsActive)
	err := c.cc.Invoke(ctx, "/api.MonitorDataService/IsUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) InitAgent(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.MonitorDataService/InitAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) HandleMonitorData(ctx context.Context, in *MonitorData, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.MonitorDataService/HandleMonitorData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) HandleCustomMonitorData(ctx context.Context, in *MonitorData, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.MonitorDataService/HandleCustomMonitorData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) HandleMonitorDataRequest(ctx context.Context, in *MonitorDataRequest, opts ...grpc.CallOption) (*MonitorData, error) {
	out := new(MonitorData)
	err := c.cc.Invoke(ctx, "/api.MonitorDataService/HandleMonitorDataRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) HandleCustomMetricNameRequest(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.MonitorDataService/HandleCustomMetricNameRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) HandleAgentIdsRequest(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.MonitorDataService/HandleAgentIdsRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorDataServiceServer is the server API for MonitorDataService service.
type MonitorDataServiceServer interface {
	HandlePing(context.Context, *ServerInfo) (*Message, error)
	IsUp(context.Context, *ServerInfo) (*IsActive, error)
	InitAgent(context.Context, *ServerInfo) (*Message, error)
	HandleMonitorData(context.Context, *MonitorData) (*Message, error)
	HandleCustomMonitorData(context.Context, *MonitorData) (*Message, error)
	HandleMonitorDataRequest(context.Context, *MonitorDataRequest) (*MonitorData, error)
	HandleCustomMetricNameRequest(context.Context, *ServerInfo) (*Message, error)
	HandleAgentIdsRequest(context.Context, *Void) (*Message, error)
}

// UnimplementedMonitorDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorDataServiceServer struct {
}

func (*UnimplementedMonitorDataServiceServer) HandlePing(context.Context, *ServerInfo) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePing not implemented")
}
func (*UnimplementedMonitorDataServiceServer) IsUp(context.Context, *ServerInfo) (*IsActive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUp not implemented")
}
func (*UnimplementedMonitorDataServiceServer) InitAgent(context.Context, *ServerInfo) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitAgent not implemented")
}
func (*UnimplementedMonitorDataServiceServer) HandleMonitorData(context.Context, *MonitorData) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleMonitorData not implemented")
}
func (*UnimplementedMonitorDataServiceServer) HandleCustomMonitorData(context.Context, *MonitorData) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCustomMonitorData not implemented")
}
func (*UnimplementedMonitorDataServiceServer) HandleMonitorDataRequest(context.Context, *MonitorDataRequest) (*MonitorData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleMonitorDataRequest not implemented")
}
func (*UnimplementedMonitorDataServiceServer) HandleCustomMetricNameRequest(context.Context, *ServerInfo) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCustomMetricNameRequest not implemented")
}
func (*UnimplementedMonitorDataServiceServer) HandleAgentIdsRequest(context.Context, *Void) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAgentIdsRequest not implemented")
}

func RegisterMonitorDataServiceServer(s *grpc.Server, srv MonitorDataServiceServer) {
	s.RegisterService(&_MonitorDataService_serviceDesc, srv)
}

func _MonitorDataService_HandlePing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandlePing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MonitorDataService/HandlePing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandlePing(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_IsUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).IsUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MonitorDataService/IsUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).IsUp(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_InitAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).InitAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MonitorDataService/InitAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).InitAgent(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_HandleMonitorData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandleMonitorData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MonitorDataService/HandleMonitorData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandleMonitorData(ctx, req.(*MonitorData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_HandleCustomMonitorData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandleCustomMonitorData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MonitorDataService/HandleCustomMonitorData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandleCustomMonitorData(ctx, req.(*MonitorData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_HandleMonitorDataRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandleMonitorDataRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MonitorDataService/HandleMonitorDataRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandleMonitorDataRequest(ctx, req.(*MonitorDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_HandleCustomMetricNameRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandleCustomMetricNameRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MonitorDataService/HandleCustomMetricNameRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandleCustomMetricNameRequest(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_HandleAgentIdsRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandleAgentIdsRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MonitorDataService/HandleAgentIdsRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandleAgentIdsRequest(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MonitorDataService",
	HandlerType: (*MonitorDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandlePing",
			Handler:    _MonitorDataService_HandlePing_Handler,
		},
		{
			MethodName: "IsUp",
			Handler:    _MonitorDataService_IsUp_Handler,
		},
		{
			MethodName: "InitAgent",
			Handler:    _MonitorDataService_InitAgent_Handler,
		},
		{
			MethodName: "HandleMonitorData",
			Handler:    _MonitorDataService_HandleMonitorData_Handler,
		},
		{
			MethodName: "HandleCustomMonitorData",
			Handler:    _MonitorDataService_HandleCustomMonitorData_Handler,
		},
		{
			MethodName: "HandleMonitorDataRequest",
			Handler:    _MonitorDataService_HandleMonitorDataRequest_Handler,
		},
		{
			MethodName: "HandleCustomMetricNameRequest",
			Handler:    _MonitorDataService_HandleCustomMetricNameRequest_Handler,
		},
		{
			MethodName: "HandleAgentIdsRequest",
			Handler:    _MonitorDataService_HandleAgentIdsRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
