// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *ServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type MonitorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorData   string                 `protobuf:"bytes,1,opt,name=monitorData,proto3" json:"monitorData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorData) Reset() {
	*x = MonitorData{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorData) ProtoMessage() {}

func (x *MonitorData) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorData.ProtoReflect.Descriptor instead.
func (*MonitorData) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *MonitorData) GetMonitorData() string {
	if x != nil {
		return x.MonitorData
	}
	return ""
}

// A new host trades a single use token for its own agent key
type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	HostName      string                 `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *EnrollRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	AgentKey      string                 `protobuf:"bytes,2,opt,name=agentKey,proto3" json:"agentKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollResponse) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *EnrollResponse) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

type HostSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Up            bool                   `protobuf:"varint,2,opt,name=up,proto3" json:"up,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	Time          int64                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Os            string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	UptimeSeconds float64                `protobuf:"fixed64,6,opt,name=uptimeSeconds,proto3" json:"uptimeSeconds,omitempty"`
	CpuPct        float64                `protobuf:"fixed64,7,opt,name=cpuPct,proto3" json:"cpuPct,omitempty"`
	MemUsedPct    float64                `protobuf:"fixed64,8,opt,name=memUsedPct,proto3" json:"memUsedPct,omitempty"`
	SwapUsedPct   float64                `protobuf:"fixed64,9,opt,name=swapUsedPct,proto3" json:"swapUsedPct,omitempty"`
	DiskUsedPct   float64                `protobuf:"fixed64,10,opt,name=diskUsedPct,proto3" json:"diskUsedPct,omitempty"`
	RxBps         float64                `protobuf:"fixed64,11,opt,name=rxBps,proto3" json:"rxBps,omitempty"`
	TxBps         float64                `protobuf:"fixed64,12,opt,name=txBps,proto3" json:"txBps,omitempty"`
	ActiveAlerts  int32                  `protobuf:"varint,13,opt,name=activeAlerts,proto3" json:"activeAlerts,omitempty"`
	// highest severity of the open alerts, 0 when there are none
	WorstSeverity int32 `protobuf:"varint,14,opt,name=worstSeverity,proto3" json:"worstSeverity,omitempty"`
	// running containers at the latest snapshot
	Containers int32 `protobuf:"varint,15,opt,name=containers,proto3" json:"containers,omitempty"`
	// days until the first disk fills up, unset when none is filling up
	DiskFullDays  *float64 `protobuf:"fixed64,16,opt,name=diskFullDays,proto3,oneof" json:"diskFullDays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostSummary) Reset() {
	*x = HostSummary{}
	mi := &file_api_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSummary) ProtoMessage() {}

func (x *HostSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSummary.ProtoReflect.Descriptor instead.
func (*HostSummary) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *HostSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostSummary) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *HostSummary) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *HostSummary) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *HostSummary) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostSummary) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HostSummary) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *HostSummary) GetMemUsedPct() float64 {
	if x != nil {
		return x.MemUsedPct
	}
	return 0
}

func (x *HostSummary) GetSwapUsedPct() float64 {
	if x != nil {
		return x.SwapUsedPct
	}
	return 0
}

func (x *HostSummary) GetDiskUsedPct() float64 {
	if x != nil {
		return x.DiskUsedPct
	}
	return 0
}

func (x *HostSummary) GetRxBps() float64 {
	if x != nil {
		return x.RxBps
	}
	return 0
}

func (x *HostSummary) GetTxBps() float64 {
	if x != nil {
		return x.TxBps
	}
	return 0
}

func (x *HostSummary) GetActiveAlerts() int32 {
	if x != nil {
		return x.ActiveAlerts
	}
	return 0
}

func (x *HostSummary) GetWorstSeverity() int32 {
	if x != nil {
		return x.WorstSeverity
	}
	return 0
}

func (x *HostSummary) GetContainers() int32 {
	if x != nil {
		return x.Containers
	}
	return 0
}

func (x *HostSummary) GetDiskFullDays() float64 {
	if x != nil && x.DiskFullDays != nil {
		return *x.DiskFullDays
	}
	return 0
}

type FleetSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostSummary         `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetSummary) Reset() {
	*x = FleetSummary{}
	mi := &file_api_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetSummary) ProtoMessage() {}

func (x *FleetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetSummary.ProtoReflect.Descriptor instead.
func (*FleetSummary) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *FleetSummary) GetHosts() []*HostSummary {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type HostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostRequest) Reset() {
	*x = HostRequest{}
	mi := &file_api_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRequest) ProtoMessage() {}

func (x *HostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRequest.ProtoReflect.Descriptor instead.
func (*HostRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{8}
}

func (x *HostRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// snapshotJson is the agent's latest MonitorData
type HostSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	SnapshotJson  string                 `protobuf:"bytes,3,opt,name=snapshotJson,proto3" json:"snapshotJson,omitempty"`
	LastSeen      int64                  `protobuf:"varint,4,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	Up            bool                   `protobuf:"varint,5,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostSnapshot) Reset() {
	*x = HostSnapshot{}
	mi := &file_api_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSnapshot) ProtoMessage() {}

func (x *HostSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSnapshot.ProtoReflect.Descriptor instead.
func (*HostSnapshot) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *HostSnapshot) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostSnapshot) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *HostSnapshot) GetSnapshotJson() string {
	if x != nil {
		return x.SnapshotJson
	}
	return ""
}

func (x *HostSnapshot) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *HostSnapshot) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

type SeriesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Host   string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Metric string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	// label keeps one series, for example a mount point or a custom metric
	Label     string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	From      int64  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	To        int64  `protobuf:"varint,5,opt,name=to,proto3" json:"to,omitempty"`
	MaxPoints int32  `protobuf:"varint,6,opt,name=maxPoints,proto3" json:"maxPoints,omitempty"`
	// max returns the peak of each bucket instead of the average
	Max           bool `protobuf:"varint,7,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesRequest) Reset() {
	*x = SeriesRequest{}
	mi := &file_api_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesRequest) ProtoMessage() {}

func (x *SeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesRequest.ProtoReflect.Descriptor instead.
func (*SeriesRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{10}
}

func (x *SeriesRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SeriesRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SeriesRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SeriesRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SeriesRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *SeriesRequest) GetMaxPoints() int32 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *SeriesRequest) GetMax() bool {
	if x != nil {
		return x.Max
	}
	return false
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_api_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{11}
}

func (x *Point) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Point) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Points        []*Point               `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_api_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{12}
}

func (x *Series) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Series) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type SeriesResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Metric string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	// source is raw, 1m or 1h
	Source        string    `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	StepSeconds   int64     `protobuf:"varint,3,opt,name=stepSeconds,proto3" json:"stepSeconds,omitempty"`
	Series        []*Series `protobuf:"bytes,4,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesResponse) Reset() {
	*x = SeriesResponse{}
	mi := &file_api_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesResponse) ProtoMessage() {}

func (x *SeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesResponse.ProtoReflect.Descriptor instead.
func (*SeriesResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{13}
}

func (x *SeriesResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SeriesResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SeriesResponse) GetStepSeconds() int64 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

func (x *SeriesResponse) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type ProcessesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Host  string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// at returns the newest snapshot at or before this time, 0 for latest
	At            int64 `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessesRequest) Reset() {
	*x = ProcessesRequest{}
	mi := &file_api_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessesRequest) ProtoMessage() {}

func (x *ProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessesRequest.ProtoReflect.Descriptor instead.
func (*ProcessesRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessesRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProcessesRequest) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

// processesJson holds the CPU and Memory top process lists
type ProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	ProcessesJson string                 `protobuf:"bytes,2,opt,name=processesJson,proto3" json:"processesJson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessesResponse) Reset() {
	*x = ProcessesResponse{}
	mi := &file_api_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessesResponse) ProtoMessage() {}

func (x *ProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessesResponse.ProtoReflect.Descriptor instead.
func (*ProcessesResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessesResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ProcessesResponse) GetProcessesJson() string {
	if x != nil {
		return x.ProcessesJson
	}
	return ""
}

type NameList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameList) Reset() {
	*x = NameList{}
	mi := &file_api_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameList) ProtoMessage() {}

func (x *NameList) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameList.ProtoReflect.Descriptor instead.
func (*NameList) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{16}
}

func (x *NameList) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type AlertsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host limits the list to one host, empty means all
	Host          string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	OpenOnly      bool   `protobuf:"varint,2,opt,name=openOnly,proto3" json:"openOnly,omitempty"`
	From          int64  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To            int64  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertsRequest) Reset() {
	*x = AlertsRequest{}
	mi := &file_api_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertsRequest) ProtoMessage() {}

func (x *AlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertsRequest.ProtoReflect.Descriptor instead.
func (*AlertsRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{17}
}

func (x *AlertsRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AlertsRequest) GetOpenOnly() bool {
	if x != nil {
		return x.OpenOnly
	}
	return false
}

func (x *AlertsRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *AlertsRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type AlertRecord struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host   string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Rule   string                 `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	Metric string                 `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	Target string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	// 1 is warning, 2 is critical
	Severity  int32   `protobuf:"varint,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Value     float64 `protobuf:"fixed64,7,opt,name=value,proto3" json:"value,omitempty"`
	StartedAt int64   `protobuf:"varint,8,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	UpdatedAt int64   `protobuf:"varint,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// 0 while the alert is open
	ResolvedAt    int64 `protobuf:"varint,10,opt,name=resolvedAt,proto3" json:"resolvedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRecord) Reset() {
	*x = AlertRecord{}
	mi := &file_api_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRecord) ProtoMessage() {}

func (x *AlertRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRecord.ProtoReflect.Descriptor instead.
func (*AlertRecord) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{18}
}

func (x *AlertRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlertRecord) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AlertRecord) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *AlertRecord) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AlertRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AlertRecord) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *AlertRecord) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AlertRecord) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *AlertRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *AlertRecord) GetResolvedAt() int64 {
	if x != nil {
		return x.ResolvedAt
	}
	return 0
}

type AlertList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*AlertRecord         `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertList) Reset() {
	*x = AlertList{}
	mi := &file_api_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertList) ProtoMessage() {}

func (x *AlertList) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertList.ProtoReflect.Descriptor instead.
func (*AlertList) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{19}
}

func (x *AlertList) GetAlerts() []*AlertRecord {
	if x != nil {
		return x.Alerts
	}
	return nil
}

// A disk's growth over the last week and when it fills up at that rate
type DiskForecast struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Device      string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mount       string                 `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	UsedPct     float64                `protobuf:"fixed64,3,opt,name=usedPct,proto3" json:"usedPct,omitempty"`
	PctPerDay   float64                `protobuf:"fixed64,4,opt,name=pctPerDay,proto3" json:"pctPerDay,omitempty"`
	BytesPerDay float64                `protobuf:"fixed64,5,opt,name=bytesPerDay,proto3" json:"bytesPerDay,omitempty"`
	// unset when the disk is not filling up
	DaysToFull    *float64 `protobuf:"fixed64,6,opt,name=daysToFull,proto3,oneof" json:"daysToFull,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskForecast) Reset() {
	*x = DiskForecast{}
	mi := &file_api_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskForecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskForecast) ProtoMessage() {}

func (x *DiskForecast) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskForecast.ProtoReflect.Descriptor instead.
func (*DiskForecast) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{20}
}

func (x *DiskForecast) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskForecast) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *DiskForecast) GetUsedPct() float64 {
	if x != nil {
		return x.UsedPct
	}
	return 0
}

func (x *DiskForecast) GetPctPerDay() float64 {
	if x != nil {
		return x.PctPerDay
	}
	return 0
}

func (x *DiskForecast) GetBytesPerDay() float64 {
	if x != nil {
		return x.BytesPerDay
	}
	return 0
}

func (x *DiskForecast) GetDaysToFull() float64 {
	if x != nil && x.DaysToFull != nil {
		return *x.DaysToFull
	}
	return 0
}

type DiskForecastList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*DiskForecast        `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskForecastList) Reset() {
	*x = DiskForecastList{}
	mi := &file_api_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskForecastList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskForecastList) ProtoMessage() {}

func (x *DiskForecastList) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskForecastList.ProtoReflect.Descriptor instead.
func (*DiskForecastList) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{21}
}

func (x *DiskForecastList) GetDisks() []*DiskForecast {
	if x != nil {
		return x.Disks
	}
	return nil
}

type ProcessUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	From          int64                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessUsageRequest) Reset() {
	*x = ProcessUsageRequest{}
	mi := &file_api_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUsageRequest) ProtoMessage() {}

func (x *ProcessUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUsageRequest.ProtoReflect.Descriptor instead.
func (*ProcessUsageRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{22}
}

func (x *ProcessUsageRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProcessUsageRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ProcessUsageRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

// One program's share of the range. Processes with the same name are
// added up per snapshot.
type ProcessUsage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CpuAvg  float64                `protobuf:"fixed64,2,opt,name=cpuAvg,proto3" json:"cpuAvg,omitempty"`
	CpuPeak float64                `protobuf:"fixed64,3,opt,name=cpuPeak,proto3" json:"cpuPeak,omitempty"`
	MemAvg  float64                `protobuf:"fixed64,4,opt,name=memAvg,proto3" json:"memAvg,omitempty"`
	MemPeak float64                `protobuf:"fixed64,5,opt,name=memPeak,proto3" json:"memPeak,omitempty"`
	// share of the snapshots the program was in the top lists
	SeenPct       float64 `protobuf:"fixed64,6,opt,name=seenPct,proto3" json:"seenPct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessUsage) Reset() {
	*x = ProcessUsage{}
	mi := &file_api_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUsage) ProtoMessage() {}

func (x *ProcessUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUsage.ProtoReflect.Descriptor instead.
func (*ProcessUsage) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{23}
}

func (x *ProcessUsage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessUsage) GetCpuAvg() float64 {
	if x != nil {
		return x.CpuAvg
	}
	return 0
}

func (x *ProcessUsage) GetCpuPeak() float64 {
	if x != nil {
		return x.CpuPeak
	}
	return 0
}

func (x *ProcessUsage) GetMemAvg() float64 {
	if x != nil {
		return x.MemAvg
	}
	return 0
}

func (x *ProcessUsage) GetMemPeak() float64 {
	if x != nil {
		return x.MemPeak
	}
	return 0
}

func (x *ProcessUsage) GetSeenPct() float64 {
	if x != nil {
		return x.SeenPct
	}
	return 0
}

type ProcessUsageList struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Snapshots int32                  `protobuf:"varint,1,opt,name=snapshots,proto3" json:"snapshots,omitempty"`
	// time of the first snapshot in the range
	FirstTime     int64           `protobuf:"varint,2,opt,name=firstTime,proto3" json:"firstTime,omitempty"`
	Processes     []*ProcessUsage `protobuf:"bytes,3,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessUsageList) Reset() {
	*x = ProcessUsageList{}
	mi := &file_api_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUsageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUsageList) ProtoMessage() {}

func (x *ProcessUsageList) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUsageList.ProtoReflect.Descriptor instead.
func (*ProcessUsageList) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{24}
}

func (x *ProcessUsageList) GetSnapshots() int32 {
	if x != nil {
		return x.Snapshots
	}
	return 0
}

func (x *ProcessUsageList) GetFirstTime() int64 {
	if x != nil {
		return x.FirstTime
	}
	return 0
}

func (x *ProcessUsageList) GetProcesses() []*ProcessUsage {
	if x != nil {
		return x.Processes
	}
	return nil
}

// The newest value of one of a host's custom metrics
type CustomValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Time          int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomValue) Reset() {
	*x = CustomValue{}
	mi := &file_api_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomValue) ProtoMessage() {}

func (x *CustomValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomValue.ProtoReflect.Descriptor instead.
func (*CustomValue) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{25}
}

func (x *CustomValue) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CustomValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomValue) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CustomValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CustomValue) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type SnapshotList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hosts []*HostSnapshot        `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	// custom metrics sent in the last 2 days
	CustomMetrics []*CustomValue `protobuf:"bytes,2,rep,name=customMetrics,proto3" json:"customMetrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotList) Reset() {
	*x = SnapshotList{}
	mi := &file_api_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotList) ProtoMessage() {}

func (x *SnapshotList) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotList.ProtoReflect.Descriptor instead.
func (*SnapshotList) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{26}
}

func (x *SnapshotList) GetHosts() []*HostSnapshot {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *SnapshotList) GetCustomMetrics() []*CustomValue {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

type EndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointsRequest) Reset() {
	*x = EndpointsRequest{}
	mi := &file_api_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointsRequest) ProtoMessage() {}

func (x *EndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointsRequest.ProtoReflect.Descriptor instead.
func (*EndpointsRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{27}
}

func (x *EndpointsRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *EndpointsRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

// An endpoint's newest check up to the end of the range, and how it did
// over the range. name is the endpoint rule's name.
type EndpointStatus struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url    string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Time   int64                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Ok     bool                   `protobuf:"varint,5,opt,name=ok,proto3" json:"ok,omitempty"`
	// 0 when there was no response
	StatusCode int32   `protobuf:"varint,6,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	LatencyMs  float64 `protobuf:"fixed64,7,opt,name=latencyMs,proto3" json:"latencyMs,omitempty"`
	Error      string  `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	Checks     int32   `protobuf:"varint,9,opt,name=checks,proto3" json:"checks,omitempty"`
	UptimePct  float64 `protobuf:"fixed64,10,opt,name=uptimePct,proto3" json:"uptimePct,omitempty"`
	// over the checks that got a response
	AvgLatencyMs  float64 `protobuf:"fixed64,11,opt,name=avgLatencyMs,proto3" json:"avgLatencyMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointStatus) Reset() {
	*x = EndpointStatus{}
	mi := &file_api_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointStatus) ProtoMessage() {}

func (x *EndpointStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointStatus.ProtoReflect.Descriptor instead.
func (*EndpointStatus) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{28}
}

func (x *EndpointStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointStatus) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EndpointStatus) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EndpointStatus) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *EndpointStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *EndpointStatus) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EndpointStatus) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *EndpointStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EndpointStatus) GetChecks() int32 {
	if x != nil {
		return x.Checks
	}
	return 0
}

func (x *EndpointStatus) GetUptimePct() float64 {
	if x != nil {
		return x.UptimePct
	}
	return 0
}

func (x *EndpointStatus) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

type EndpointList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*EndpointStatus      `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointList) Reset() {
	*x = EndpointList{}
	mi := &file_api_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointList) ProtoMessage() {}

func (x *EndpointList) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointList.ProtoReflect.Descriptor instead.
func (*EndpointList) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{29}
}

func (x *EndpointList) GetEndpoints() []*EndpointStatus {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type EndpointSeriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// latency or availability
	Metric        string `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	From          int64  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To            int64  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	MaxPoints     int32  `protobuf:"varint,5,opt,name=maxPoints,proto3" json:"maxPoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointSeriesRequest) Reset() {
	*x = EndpointSeriesRequest{}
	mi := &file_api_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSeriesRequest) ProtoMessage() {}

func (x *EndpointSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSeriesRequest.ProtoReflect.Descriptor instead.
func (*EndpointSeriesRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{30}
}

func (x *EndpointSeriesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointSeriesRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *EndpointSeriesRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *EndpointSeriesRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *EndpointSeriesRequest) GetMaxPoints() int32 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x03api\"\x06\n" +
	"\x04Void\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"H\n" +
	"\n" +
	"ServerInfo\x12\x1e\n" +
	"\n" +
	"serverName\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\"/\n" +
	"\vMonitorData\x12 \n" +
	"\vmonitorData\x18\x01 \x01(\tR\vmonitorData\"]\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostName\x18\x02 \x01(\tR\bhostName\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"H\n" +
	"\x0eEnrollResponse\x12\x1a\n" +
	"\bhostName\x18\x01 \x01(\tR\bhostName\x12\x1a\n" +
	"\bagentKey\x18\x02 \x01(\tR\bagentKey\"\xe3\x03\n" +
	"\vHostSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\bR\x02up\x12\x1a\n" +
	"\blastSeen\x18\x03 \x01(\x03R\blastSeen\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12$\n" +
	"\ruptimeSeconds\x18\x06 \x01(\x01R\ruptimeSeconds\x12\x16\n" +
	"\x06cpuPct\x18\a \x01(\x01R\x06cpuPct\x12\x1e\n" +
	"\n" +
	"memUsedPct\x18\b \x01(\x01R\n" +
	"memUsedPct\x12 \n" +
	"\vswapUsedPct\x18\t \x01(\x01R\vswapUsedPct\x12 \n" +
	"\vdiskUsedPct\x18\n" +
	" \x01(\x01R\vdiskUsedPct\x12\x14\n" +
	"\x05rxBps\x18\v \x01(\x01R\x05rxBps\x12\x14\n" +
	"\x05txBps\x18\f \x01(\x01R\x05txBps\x12\"\n" +
	"\factiveAlerts\x18\r \x01(\x05R\factiveAlerts\x12$\n" +
	"\rworstSeverity\x18\x0e \x01(\x05R\rworstSeverity\x12\x1e\n" +
	"\n" +
	"containers\x18\x0f \x01(\x05R\n" +
	"containers\x12'\n" +
	"\fdiskFullDays\x18\x10 \x01(\x01H\x00R\fdiskFullDays\x88\x01\x01B\x0f\n" +
	"\r_diskFullDays\"6\n" +
	"\fFleetSummary\x12&\n" +
	"\x05hosts\x18\x01 \x03(\v2\x10.api.HostSummaryR\x05hosts\"!\n" +
	"\vHostRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"\x86\x01\n" +
	"\fHostSnapshot\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12\"\n" +
	"\fsnapshotJson\x18\x03 \x01(\tR\fsnapshotJson\x12\x1a\n" +
	"\blastSeen\x18\x04 \x01(\x03R\blastSeen\x12\x0e\n" +
	"\x02up\x18\x05 \x01(\bR\x02up\"\xa5\x01\n" +
	"\rSeriesRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\x03R\x02to\x12\x1c\n" +
	"\tmaxPoints\x18\x06 \x01(\x05R\tmaxPoints\x12\x10\n" +
	"\x03max\x18\a \x01(\bR\x03max\"1\n" +
	"\x05Point\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"B\n" +
	"\x06Series\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\"\n" +
	"\x06points\x18\x02 \x03(\v2\n" +
	".api.PointR\x06points\"\x87\x01\n" +
	"\x0eSeriesResponse\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vstepSeconds\x18\x03 \x01(\x03R\vstepSeconds\x12#\n" +
	"\x06series\x18\x04 \x03(\v2\v.api.SeriesR\x06series\"6\n" +
	"\x10ProcessesRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\x03R\x02at\"M\n" +
	"\x11ProcessesResponse\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12$\n" +
	"\rprocessesJson\x18\x02 \x01(\tR\rprocessesJson\" \n" +
	"\bNameList\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"c\n" +
	"\rAlertsRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\bopenOnly\x18\x02 \x01(\bR\bopenOnly\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\"\x83\x02\n" +
	"\vAlertRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\x12\x16\n" +
	"\x06metric\x18\x04 \x01(\tR\x06metric\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\x05R\bseverity\x12\x14\n" +
	"\x05value\x18\a \x01(\x01R\x05value\x12\x1c\n" +
	"\tstartedAt\x18\b \x01(\x03R\tstartedAt\x12\x1c\n" +
	"\tupdatedAt\x18\t \x01(\x03R\tupdatedAt\x12\x1e\n" +
	"\n" +
	"resolvedAt\x18\n" +
	" \x01(\x03R\n" +
	"resolvedAt\"5\n" +
	"\tAlertList\x12(\n" +
	"\x06alerts\x18\x01 \x03(\v2\x10.api.AlertRecordR\x06alerts\"\xca\x01\n" +
	"\fDiskForecast\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05mount\x18\x02 \x01(\tR\x05mount\x12\x18\n" +
	"\ausedPct\x18\x03 \x01(\x01R\ausedPct\x12\x1c\n" +
	"\tpctPerDay\x18\x04 \x01(\x01R\tpctPerDay\x12 \n" +
	"\vbytesPerDay\x18\x05 \x01(\x01R\vbytesPerDay\x12#\n" +
	"\n" +
	"daysToFull\x18\x06 \x01(\x01H\x00R\n" +
	"daysToFull\x88\x01\x01B\r\n" +
	"\v_daysToFull\";\n" +
	"\x10DiskForecastList\x12'\n" +
	"\x05disks\x18\x01 \x03(\v2\x11.api.DiskForecastR\x05disks\"M\n" +
	"\x13ProcessUsageRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x03R\x02to\"\xa0\x01\n" +
	"\fProcessUsage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06cpuAvg\x18\x02 \x01(\x01R\x06cpuAvg\x12\x18\n" +
	"\acpuPeak\x18\x03 \x01(\x01R\acpuPeak\x12\x16\n" +
	"\x06memAvg\x18\x04 \x01(\x01R\x06memAvg\x12\x18\n" +
	"\amemPeak\x18\x05 \x01(\x01R\amemPeak\x12\x18\n" +
	"\aseenPct\x18\x06 \x01(\x01R\aseenPct\"\x7f\n" +
	"\x10ProcessUsageList\x12\x1c\n" +
	"\tsnapshots\x18\x01 \x01(\x05R\tsnapshots\x12\x1c\n" +
	"\tfirstTime\x18\x02 \x01(\x03R\tfirstTime\x12/\n" +
	"\tprocesses\x18\x03 \x03(\v2\x11.api.ProcessUsageR\tprocesses\"s\n" +
	"\vCustomValue\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time\"o\n" +
	"\fSnapshotList\x12'\n" +
	"\x05hosts\x18\x01 \x03(\v2\x11.api.HostSnapshotR\x05hosts\x126\n" +
	"\rcustomMetrics\x18\x02 \x03(\v2\x10.api.CustomValueR\rcustomMetrics\"6\n" +
	"\x10EndpointsRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\"\xa0\x02\n" +
	"\x0eEndpointStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\x12\x0e\n" +
	"\x02ok\x18\x05 \x01(\bR\x02ok\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x06 \x01(\x05R\n" +
	"statusCode\x12\x1c\n" +
	"\tlatencyMs\x18\a \x01(\x01R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x16\n" +
	"\x06checks\x18\t \x01(\x05R\x06checks\x12\x1c\n" +
	"\tuptimePct\x18\n" +
	" \x01(\x01R\tuptimePct\x12\"\n" +
	"\favgLatencyMs\x18\v \x01(\x01R\favgLatencyMs\"A\n" +
	"\fEndpointList\x121\n" +
	"\tendpoints\x18\x01 \x03(\v2\x13.api.EndpointStatusR\tendpoints\"\x85\x01\n" +
	"\x15EndpointSeriesRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\x12\x1c\n" +
	"\tmaxPoints\x18\x05 \x01(\x05R\tmaxPoints2\x80\a\n" +
	"\x12MonitorDataService\x123\n" +
	"\x06Enroll\x12\x12.api.EnrollRequest\x1a\x13.api.EnrollResponse\"\x00\x12-\n" +
	"\n" +
	"HandlePing\x12\x0f.api.ServerInfo\x1a\f.api.Message\"\x00\x12,\n" +
	"\tInitAgent\x12\x0f.api.ServerInfo\x1a\f.api.Message\"\x00\x125\n" +
	"\x11HandleMonitorData\x12\x10.api.MonitorData\x1a\f.api.Message\"\x00\x12;\n" +
	"\x17HandleCustomMonitorData\x12\x10.api.MonitorData\x1a\f.api.Message\"\x00\x12'\n" +
	"\x05Fleet\x12\t.api.Void\x1a\x11.api.FleetSummary\"\x00\x121\n" +
	"\bSnapshot\x12\x10.api.HostRequest\x1a\x11.api.HostSnapshot\"\x00\x128\n" +
	"\vQuerySeries\x12\x12.api.SeriesRequest\x1a\x13.api.SeriesResponse\"\x00\x12<\n" +
	"\tProcesses\x12\x15.api.ProcessesRequest\x1a\x16.api.ProcessesResponse\"\x00\x126\n" +
	"\x11CustomMetricNames\x12\x10.api.HostRequest\x1a\r.api.NameList\"\x00\x12.\n" +
	"\x06Alerts\x12\x12.api.AlertsRequest\x1a\x0e.api.AlertList\"\x00\x12:\n" +
	"\rDiskForecasts\x12\x10.api.HostRequest\x1a\x15.api.DiskForecastList\"\x00\x12A\n" +
	"\fProcessUsage\x12\x18.api.ProcessUsageRequest\x1a\x15.api.ProcessUsageList\"\x00\x12+\n" +
	"\tSnapshots\x12\t.api.Void\x1a\x11.api.SnapshotList\"\x00\x127\n" +
	"\tEndpoints\x12\x15.api.EndpointsRequest\x1a\x11.api.EndpointList\"\x00\x12C\n" +
	"\x0eEndpointSeries\x12\x1a.api.EndpointSeriesRequest\x1a\x13.api.SeriesResponse\"\x00B)Z'github.com/dhamith93/SyMon/internal/apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_api_api_proto_goTypes = []any{
	(*Void)(nil),                  // 0: api.Void
	(*Message)(nil),               // 1: api.Message
	(*ServerInfo)(nil),            // 2: api.ServerInfo
	(*MonitorData)(nil),           // 3: api.MonitorData
	(*EnrollRequest)(nil),         // 4: api.EnrollRequest
	(*EnrollResponse)(nil),        // 5: api.EnrollResponse
	(*HostSummary)(nil),           // 6: api.HostSummary
	(*FleetSummary)(nil),          // 7: api.FleetSummary
	(*HostRequest)(nil),           // 8: api.HostRequest
	(*HostSnapshot)(nil),          // 9: api.HostSnapshot
	(*SeriesRequest)(nil),         // 10: api.SeriesRequest
	(*Point)(nil),                 // 11: api.Point
	(*Series)(nil),                // 12: api.Series
	(*SeriesResponse)(nil),        // 13: api.SeriesResponse
	(*ProcessesRequest)(nil),      // 14: api.ProcessesRequest
	(*ProcessesResponse)(nil),     // 15: api.ProcessesResponse
	(*NameList)(nil),              // 16: api.NameList
	(*AlertsRequest)(nil),         // 17: api.AlertsRequest
	(*AlertRecord)(nil),           // 18: api.AlertRecord
	(*AlertList)(nil),             // 19: api.AlertList
	(*DiskForecast)(nil),          // 20: api.DiskForecast
	(*DiskForecastList)(nil),      // 21: api.DiskForecastList
	(*ProcessUsageRequest)(nil),   // 22: api.ProcessUsageRequest
	(*ProcessUsage)(nil),          // 23: api.ProcessUsage
	(*ProcessUsageList)(nil),      // 24: api.ProcessUsageList
	(*CustomValue)(nil),           // 25: api.CustomValue
	(*SnapshotList)(nil),          // 26: api.SnapshotList
	(*EndpointsRequest)(nil),      // 27: api.EndpointsRequest
	(*EndpointStatus)(nil),        // 28: api.EndpointStatus
	(*EndpointList)(nil),          // 29: api.EndpointList
	(*EndpointSeriesRequest)(nil), // 30: api.EndpointSeriesRequest
}
var file_api_api_proto_depIdxs = []int32{
	6,  // 0: api.FleetSummary.hosts:type_name -> api.HostSummary
	11, // 1: api.Series.points:type_name -> api.Point
	12, // 2: api.SeriesResponse.series:type_name -> api.Series
	18, // 3: api.AlertList.alerts:type_name -> api.AlertRecord
	20, // 4: api.DiskForecastList.disks:type_name -> api.DiskForecast
	23, // 5: api.ProcessUsageList.processes:type_name -> api.ProcessUsage
	9,  // 6: api.SnapshotList.hosts:type_name -> api.HostSnapshot
	25, // 7: api.SnapshotList.customMetrics:type_name -> api.CustomValue
	28, // 8: api.EndpointList.endpoints:type_name -> api.EndpointStatus
	4,  // 9: api.MonitorDataService.Enroll:input_type -> api.EnrollRequest
	2,  // 10: api.MonitorDataService.HandlePing:input_type -> api.ServerInfo
	2,  // 11: api.MonitorDataService.InitAgent:input_type -> api.ServerInfo
	3,  // 12: api.MonitorDataService.HandleMonitorData:input_type -> api.MonitorData
	3,  // 13: api.MonitorDataService.HandleCustomMonitorData:input_type -> api.MonitorData
	0,  // 14: api.MonitorDataService.Fleet:input_type -> api.Void
	8,  // 15: api.MonitorDataService.Snapshot:input_type -> api.HostRequest
	10, // 16: api.MonitorDataService.QuerySeries:input_type -> api.SeriesRequest
	14, // 17: api.MonitorDataService.Processes:input_type -> api.ProcessesRequest
	8,  // 18: api.MonitorDataService.CustomMetricNames:input_type -> api.HostRequest
	17, // 19: api.MonitorDataService.Alerts:input_type -> api.AlertsRequest
	8,  // 20: api.MonitorDataService.DiskForecasts:input_type -> api.HostRequest
	22, // 21: api.MonitorDataService.ProcessUsage:input_type -> api.ProcessUsageRequest
	0,  // 22: api.MonitorDataService.Snapshots:input_type -> api.Void
	27, // 23: api.MonitorDataService.Endpoints:input_type -> api.EndpointsRequest
	30, // 24: api.MonitorDataService.EndpointSeries:input_type -> api.EndpointSeriesRequest
	5,  // 25: api.MonitorDataService.Enroll:output_type -> api.EnrollResponse
	1,  // 26: api.MonitorDataService.HandlePing:output_type -> api.Message
	1,  // 27: api.MonitorDataService.InitAgent:output_type -> api.Message
	1,  // 28: api.MonitorDataService.HandleMonitorData:output_type -> api.Message
	1,  // 29: api.MonitorDataService.HandleCustomMonitorData:output_type -> api.Message
	7,  // 30: api.MonitorDataService.Fleet:output_type -> api.FleetSummary
	9,  // 31: api.MonitorDataService.Snapshot:output_type -> api.HostSnapshot
	13, // 32: api.MonitorDataService.QuerySeries:output_type -> api.SeriesResponse
	15, // 33: api.MonitorDataService.Processes:output_type -> api.ProcessesResponse
	16, // 34: api.MonitorDataService.CustomMetricNames:output_type -> api.NameList
	19, // 35: api.MonitorDataService.Alerts:output_type -> api.AlertList
	21, // 36: api.MonitorDataService.DiskForecasts:output_type -> api.DiskForecastList
	24, // 37: api.MonitorDataService.ProcessUsage:output_type -> api.ProcessUsageList
	26, // 38: api.MonitorDataService.Snapshots:output_type -> api.SnapshotList
	29, // 39: api.MonitorDataService.Endpoints:output_type -> api.EndpointList
	13, // 40: api.MonitorDataService.EndpointSeries:output_type -> api.SeriesResponse
	25, // [25:41] is the sub-list for method output_type
	9,  // [9:25] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	file_api_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_api_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
