// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type IsActive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUp          bool                   `protobuf:"varint,1,opt,name=isUp,proto3" json:"isUp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsActive) Reset() {
	*x = IsActive{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsActive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsActive) ProtoMessage() {}

func (x *IsActive) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsActive.ProtoReflect.Descriptor instead.
func (*IsActive) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *IsActive) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type MonitorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorData   string                 `protobuf:"bytes,1,opt,name=monitorData,proto3" json:"monitorData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorData) Reset() {
	*x = MonitorData{}
	mi := &file_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorData) ProtoMessage() {}

func (x *MonitorData) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorData.ProtoReflect.Descriptor instead.
func (*MonitorData) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *MonitorData) GetMonitorData() string {
	if x != nil {
		return x.MonitorData
	}
	return ""
}

type MonitorDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerName     string                 `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	LogType        string                 `protobuf:"bytes,2,opt,name=logType,proto3" json:"logType,omitempty"`
	From           int64                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To             int64                  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	Time           int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	IsCustomMetric bool                   `protobuf:"varint,6,opt,name=isCustomMetric,proto3" json:"isCustomMetric,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MonitorDataRequest) Reset() {
	*x = MonitorDataRequest{}
	mi := &file_api_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorDataRequest) ProtoMessage() {}

func (x *MonitorDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorDataRequest.ProtoReflect.Descriptor instead.
func (*MonitorDataRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *MonitorDataRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *MonitorDataRequest) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *MonitorDataRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MonitorDataRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *MonitorDataRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *MonitorDataRequest) GetIsCustomMetric() bool {
	if x != nil {
		return x.IsCustomMetric
	}
	return false
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x03api\"\x06\n" +
	"\x04Void\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"\x1e\n" +
	"\bIsActive\x12\x12\n" +
	"\x04isUp\x18\x01 \x01(\bR\x04isUp\"H\n" +
	"\n" +
	"ServerInfo\x12\x1e\n" +
	"\n" +
	"serverName\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\"/\n" +
	"\vMonitorData\x12 \n" +
	"\vmonitorData\x18\x01 \x01(\tR\vmonitorData\"\xae\x01\n" +
	"\x12MonitorDataRequest\x12\x1e\n" +
	"\n" +
	"serverName\x18\x01 \x01(\tR\n" +
	"serverName\x12\x18\n" +
	"\alogType\x18\x02 \x01(\tR\alogType\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time\x12&\n" +
	"\x0eisCustomMetric\x18\x06 \x01(\bR\x0eisCustomMetric2\xce\x03\n" +
	"\x12MonitorDataService\x12-\n" +
	"\n" +
	"HandlePing\x12\x0f.api.ServerInfo\x1a\f.api.Message\"\x00\x12(\n" +
	"\x04IsUp\x12\x0f.api.ServerInfo\x1a\r.api.IsActive\"\x00\x12,\n" +
	"\tInitAgent\x12\x0f.api.ServerInfo\x1a\f.api.Message\"\x00\x125\n" +
	"\x11HandleMonitorData\x12\x10.api.MonitorData\x1a\f.api.Message\"\x00\x12;\n" +
	"\x17HandleCustomMonitorData\x12\x10.api.MonitorData\x1a\f.api.Message\"\x00\x12G\n" +
	"\x18HandleMonitorDataRequest\x12\x17.api.MonitorDataRequest\x1a\x10.api.MonitorData\"\x00\x12@\n" +
	"\x1dHandleCustomMetricNameRequest\x12\x0f.api.ServerInfo\x1a\f.api.Message\"\x00\x122\n" +
	"\x15HandleAgentIdsRequest\x12\t.api.Void\x1a\f.api.Message\"\x00B)Z'github.com/dhamith93/SyMon/internal/apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_api_proto_goTypes = []any{
	(*Void)(nil),               // 0: api.Void
	(*Message)(nil),            // 1: api.Message
	(*IsActive)(nil),           // 2: api.IsActive
	(*ServerInfo)(nil),         // 3: api.ServerInfo
	(*MonitorData)(nil),        // 4: api.MonitorData
	(*MonitorDataRequest)(nil), // 5: api.MonitorDataRequest
}
var file_api_api_proto_depIdxs = []int32{
	3, // 0: api.MonitorDataService.HandlePing:input_type -> api.ServerInfo
	3, // 1: api.MonitorDataService.IsUp:input_type -> api.ServerInfo
	3, // 2: api.MonitorDataService.InitAgent:input_type -> api.ServerInfo
	4, // 3: api.MonitorDataService.HandleMonitorData:input_type -> api.MonitorData
	4, // 4: api.MonitorDataService.HandleCustomMonitorData:input_type -> api.MonitorData
	5, // 5: api.MonitorDataService.HandleMonitorDataRequest:input_type -> api.MonitorDataRequest
	3, // 6: api.MonitorDataService.HandleCustomMetricNameRequest:input_type -> api.ServerInfo
	0, // 7: api.MonitorDataService.HandleAgentIdsRequest:input_type -> api.Void
	1, // 8: api.MonitorDataService.HandlePing:output_type -> api.Message
	2, // 9: api.MonitorDataService.IsUp:output_type -> api.IsActive
	1, // 10: api.MonitorDataService.InitAgent:output_type -> api.Message
	1, // 11: api.MonitorDataService.HandleMonitorData:output_type -> api.Message
	1, // 12: api.MonitorDataService.HandleCustomMonitorData:output_type -> api.Message
	4, // 13: api.MonitorDataService.HandleMonitorDataRequest:output_type -> api.MonitorData
	1, // 14: api.MonitorDataService.HandleCustomMetricNameRequest:output_type -> api.Message
	1, // 15: api.MonitorDataService.HandleAgentIdsRequest:output_type -> api.Message
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
