// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitorDataService_HandlePing_FullMethodName              = "/api.MonitorDataService/HandlePing"
	MonitorDataService_InitAgent_FullMethodName               = "/api.MonitorDataService/InitAgent"
	MonitorDataService_HandleMonitorData_FullMethodName       = "/api.MonitorDataService/HandleMonitorData"
	MonitorDataService_HandleCustomMonitorData_FullMethodName = "/api.MonitorDataService/HandleCustomMonitorData"
	MonitorDataService_Fleet_FullMethodName                   = "/api.MonitorDataService/Fleet"
	MonitorDataService_Snapshot_FullMethodName                = "/api.MonitorDataService/Snapshot"
	MonitorDataService_QuerySeries_FullMethodName             = "/api.MonitorDataService/QuerySeries"
	MonitorDataService_Processes_FullMethodName               = "/api.MonitorDataService/Processes"
	MonitorDataService_CustomMetricNames_FullMethodName       = "/api.MonitorDataService/CustomMetricNames"
	MonitorDataService_Alerts_FullMethodName                  = "/api.MonitorDataService/Alerts"
)

// MonitorDataServiceClient is the client API for MonitorDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorDataServiceClient interface {
	// agent
	HandlePing(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error)
	InitAgent(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error)
	HandleMonitorData(ctx context.Context, in *MonitorData, opts ...grpc.CallOption) (*Message, error)
	HandleCustomMonitorData(ctx context.Context, in *MonitorData, opts ...grpc.CallOption) (*Message, error)
	// query api
	Fleet(ctx context.Context, in *Void, opts ...grpc.CallOption) (*FleetSummary, error)
	Snapshot(ctx context.Context, in *HostRequest, opts ...grpc.CallOption) (*HostSnapshot, error)
	QuerySeries(ctx context.Context, in *SeriesRequest, opts ...grpc.CallOption) (*SeriesResponse, error)
	Processes(ctx context.Context, in *ProcessesRequest, opts ...grpc.CallOption) (*ProcessesResponse, error)
	CustomMetricNames(ctx context.Context, in *HostRequest, opts ...grpc.CallOption) (*NameList, error)
	Alerts(ctx context.Context, in *AlertsRequest, opts ...grpc.CallOption) (*AlertList, error)
}

type monitorDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorDataServiceClient(cc grpc.ClientConnInterface) MonitorDataServiceClient {
	return &monitorDataServiceClient{cc}
}

func (c *monitorDataServiceClient) HandlePing(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MonitorDataService_HandlePing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) InitAgent(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MonitorDataService_InitAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) HandleMonitorData(ctx context.Context, in *MonitorData, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MonitorDataService_HandleMonitorData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) HandleCustomMonitorData(ctx context.Context, in *MonitorData, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MonitorDataService_HandleCustomMonitorData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) Fleet(ctx context.Context, in *Void, opts ...grpc.CallOption) (*FleetSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FleetSummary)
	err := c.cc.Invoke(ctx, MonitorDataService_Fleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) Snapshot(ctx context.Context, in *HostRequest, opts ...grpc.CallOption) (*HostSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostSnapshot)
	err := c.cc.Invoke(ctx, MonitorDataService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) QuerySeries(ctx context.Context, in *SeriesRequest, opts ...grpc.CallOption) (*SeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeriesResponse)
	err := c.cc.Invoke(ctx, MonitorDataService_QuerySeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) Processes(ctx context.Context, in *ProcessesRequest, opts ...grpc.CallOption) (*ProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessesResponse)
	err := c.cc.Invoke(ctx, MonitorDataService_Processes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) CustomMetricNames(ctx context.Context, in *HostRequest, opts ...grpc.CallOption) (*NameList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameList)
	err := c.cc.Invoke(ctx, MonitorDataService_CustomMetricNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorDataServiceClient) Alerts(ctx context.Context, in *AlertsRequest, opts ...grpc.CallOption) (*AlertList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertList)
	err := c.cc.Invoke(ctx, MonitorDataService_Alerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorDataServiceServer is the server API for MonitorDataService service.
// All implementations must embed UnimplementedMonitorDataServiceServer
// for forward compatibility.
type MonitorDataServiceServer interface {
	// agent
	HandlePing(context.Context, *ServerInfo) (*Message, error)
	InitAgent(context.Context, *ServerInfo) (*Message, error)
	HandleMonitorData(context.Context, *MonitorData) (*Message, error)
	HandleCustomMonitorData(context.Context, *MonitorData) (*Message, error)
	// query api
	Fleet(context.Context, *Void) (*FleetSummary, error)
	Snapshot(context.Context, *HostRequest) (*HostSnapshot, error)
	QuerySeries(context.Context, *SeriesRequest) (*SeriesResponse, error)
	Processes(context.Context, *ProcessesRequest) (*ProcessesResponse, error)
	CustomMetricNames(context.Context, *HostRequest) (*NameList, error)
	Alerts(context.Context, *AlertsRequest) (*AlertList, error)
	mustEmbedUnimplementedMonitorDataServiceServer()
}

// UnimplementedMonitorDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorDataServiceServer struct{}

func (UnimplementedMonitorDataServiceServer) HandlePing(context.Context, *ServerInfo) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePing not implemented")
}
func (UnimplementedMonitorDataServiceServer) InitAgent(context.Context, *ServerInfo) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitAgent not implemented")
}
func (UnimplementedMonitorDataServiceServer) HandleMonitorData(context.Context, *MonitorData) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleMonitorData not implemented")
}
func (UnimplementedMonitorDataServiceServer) HandleCustomMonitorData(context.Context, *MonitorData) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCustomMonitorData not implemented")
}
func (UnimplementedMonitorDataServiceServer) Fleet(context.Context, *Void) (*FleetSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fleet not implemented")
}
func (UnimplementedMonitorDataServiceServer) Snapshot(context.Context, *HostRequest) (*HostSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedMonitorDataServiceServer) QuerySeries(context.Context, *SeriesRequest) (*SeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySeries not implemented")
}
func (UnimplementedMonitorDataServiceServer) Processes(context.Context, *ProcessesRequest) (*ProcessesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Processes not implemented")
}
func (UnimplementedMonitorDataServiceServer) CustomMetricNames(context.Context, *HostRequest) (*NameList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomMetricNames not implemented")
}
func (UnimplementedMonitorDataServiceServer) Alerts(context.Context, *AlertsRequest) (*AlertList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alerts not implemented")
}
func (UnimplementedMonitorDataServiceServer) mustEmbedUnimplementedMonitorDataServiceServer() {}
func (UnimplementedMonitorDataServiceServer) testEmbeddedByValue()                            {}

// UnsafeMonitorDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorDataServiceServer will
// result in compilation errors.
type UnsafeMonitorDataServiceServer interface {
	mustEmbedUnimplementedMonitorDataServiceServer()
}

func RegisterMonitorDataServiceServer(s grpc.ServiceRegistrar, srv MonitorDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitorDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitorDataService_ServiceDesc, srv)
}

func _MonitorDataService_HandlePing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandlePing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_HandlePing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandlePing(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_InitAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).InitAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_InitAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).InitAgent(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_HandleMonitorData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandleMonitorData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_HandleMonitorData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandleMonitorData(ctx, req.(*MonitorData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_HandleCustomMonitorData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).HandleCustomMonitorData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_HandleCustomMonitorData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).HandleCustomMonitorData(ctx, req.(*MonitorData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_Fleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).Fleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_Fleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).Fleet(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).Snapshot(ctx, req.(*HostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_QuerySeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).QuerySeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_QuerySeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).QuerySeries(ctx, req.(*SeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_Processes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).Processes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_Processes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).Processes(ctx, req.(*ProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_CustomMetricNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).CustomMetricNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_CustomMetricNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).CustomMetricNames(ctx, req.(*HostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorDataService_Alerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorDataServiceServer).Alerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorDataService_Alerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorDataServiceServer).Alerts(ctx, req.(*AlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorDataService_ServiceDesc is the grpc.ServiceDesc for MonitorDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.MonitorDataService",
	HandlerType: (*MonitorDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandlePing",
			Handler:    _MonitorDataService_HandlePing_Handler,
		},
		{
			MethodName: "InitAgent",
			Handler:    _MonitorDataService_InitAgent_Handler,
		},
		{
			MethodName: "HandleMonitorData",
			Handler:    _MonitorDataService_HandleMonitorData_Handler,
		},
		{
			MethodName: "HandleCustomMonitorData",
			Handler:    _MonitorDataService_HandleCustomMonitorData_Handler,
		},
		{
			MethodName: "Fleet",
			Handler:    _MonitorDataService_Fleet_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _MonitorDataService_Snapshot_Handler,
		},
		{
			MethodName: "QuerySeries",
			Handler:    _MonitorDataService_QuerySeries_Handler,
		},
		{
			MethodName: "Processes",
			Handler:    _MonitorDataService_Processes_Handler,
		},
		{
			MethodName: "CustomMetricNames",
			Handler:    _MonitorDataService_CustomMetricNames_Handler,
		},
		{
			MethodName: "Alerts",
			Handler:    _MonitorDataService_Alerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
