// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: alertapi/alertapi.proto

package alertapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_alertapi_alertapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_alertapi_alertapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_alertapi_alertapi_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_alertapi_alertapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_alertapi_alertapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_alertapi_alertapi_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metricName,proto3" json:"metricName,omitempty"`
	LogId         int64                  `protobuf:"varint,3,opt,name=logId,proto3" json:"logId,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Resolved      bool                   `protobuf:"varint,8,opt,name=resolved,proto3" json:"resolved,omitempty"`
	Disk          string                 `protobuf:"bytes,9,opt,name=disk,proto3" json:"disk,omitempty"`
	Service       string                 `protobuf:"bytes,10,opt,name=service,proto3" json:"service,omitempty"`
	Pagerduty     bool                   `protobuf:"varint,11,opt,name=pagerduty,proto3" json:"pagerduty,omitempty"`
	Email         bool                   `protobuf:"varint,12,opt,name=email,proto3" json:"email,omitempty"`
	Slack         bool                   `protobuf:"varint,13,opt,name=slack,proto3" json:"slack,omitempty"`
	SlackChannel  string                 `protobuf:"bytes,14,opt,name=slackChannel,proto3" json:"slackChannel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alertapi_alertapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alertapi_alertapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alertapi_alertapi_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Alert) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Alert) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *Alert) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Alert) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Alert) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Alert) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Alert) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

func (x *Alert) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

func (x *Alert) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Alert) GetPagerduty() bool {
	if x != nil {
		return x.Pagerduty
	}
	return false
}

func (x *Alert) GetEmail() bool {
	if x != nil {
		return x.Email
	}
	return false
}

func (x *Alert) GetSlack() bool {
	if x != nil {
		return x.Slack
	}
	return false
}

func (x *Alert) GetSlackChannel() string {
	if x != nil {
		return x.SlackChannel
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=serverName,proto3" json:"serverName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_alertapi_alertapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_alertapi_alertapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_alertapi_alertapi_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type AlertArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertArray) Reset() {
	*x = AlertArray{}
	mi := &file_alertapi_alertapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertArray) ProtoMessage() {}

func (x *AlertArray) ProtoReflect() protoreflect.Message {
	mi := &file_alertapi_alertapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertArray.ProtoReflect.Descriptor instead.
func (*AlertArray) Descriptor() ([]byte, []int) {
	return file_alertapi_alertapi_proto_rawDescGZIP(), []int{4}
}

func (x *AlertArray) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_alertapi_alertapi_proto protoreflect.FileDescriptor

const file_alertapi_alertapi_proto_rawDesc = "" +
	"\n" +
	"\x17alertapi/alertapi.proto\x12\balertapi\"\x06\n" +
	"\x04Void\"6\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xff\x02\n" +
	"\x05Alert\x12\x1e\n" +
	"\n" +
	"serverName\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1e\n" +
	"\n" +
	"metricName\x18\x02 \x01(\tR\n" +
	"metricName\x12\x14\n" +
	"\x05logId\x18\x03 \x01(\x03R\x05logId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x1a\n" +
	"\bresolved\x18\b \x01(\bR\bresolved\x12\x12\n" +
	"\x04disk\x18\t \x01(\tR\x04disk\x12\x18\n" +
	"\aservice\x18\n" +
	" \x01(\tR\aservice\x12\x1c\n" +
	"\tpagerduty\x18\v \x01(\bR\tpagerduty\x12\x14\n" +
	"\x05email\x18\f \x01(\bR\x05email\x12\x14\n" +
	"\x05slack\x18\r \x01(\bR\x05slack\x12\"\n" +
	"\fslackChannel\x18\x0e \x01(\tR\fslackChannel\")\n" +
	"\aRequest\x12\x1e\n" +
	"\n" +
	"serverName\x18\x01 \x01(\tR\n" +
	"serverName\"5\n" +
	"\n" +
	"AlertArray\x12'\n" +
	"\x06alerts\x18\x01 \x03(\v2\x0f.alertapi.AlertR\x06alerts2\x80\x01\n" +
	"\fAlertService\x125\n" +
	"\fHandleAlerts\x12\x0f.alertapi.Alert\x1a\x12.alertapi.Response\"\x00\x129\n" +
	"\fAlertRequest\x12\x11.alertapi.Request\x1a\x14.alertapi.AlertArray\"\x00B.Z,github.com/dhamith93/SyMon/internal/alertapib\x06proto3"

var (
	file_alertapi_alertapi_proto_rawDescOnce sync.Once
	file_alertapi_alertapi_proto_rawDescData []byte
)

func file_alertapi_alertapi_proto_rawDescGZIP() []byte {
	file_alertapi_alertapi_proto_rawDescOnce.Do(func() {
		file_alertapi_alertapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alertapi_alertapi_proto_rawDesc), len(file_alertapi_alertapi_proto_rawDesc)))
	})
	return file_alertapi_alertapi_proto_rawDescData
}

var file_alertapi_alertapi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_alertapi_alertapi_proto_goTypes = []any{
	(*Void)(nil),       // 0: alertapi.Void
	(*Response)(nil),   // 1: alertapi.Response
	(*Alert)(nil),      // 2: alertapi.Alert
	(*Request)(nil),    // 3: alertapi.Request
	(*AlertArray)(nil), // 4: alertapi.AlertArray
}
var file_alertapi_alertapi_proto_depIdxs = []int32{
	2, // 0: alertapi.AlertArray.alerts:type_name -> alertapi.Alert
	2, // 1: alertapi.AlertService.HandleAlerts:input_type -> alertapi.Alert
	3, // 2: alertapi.AlertService.AlertRequest:input_type -> alertapi.Request
	1, // 3: alertapi.AlertService.HandleAlerts:output_type -> alertapi.Response
	4, // 4: alertapi.AlertService.AlertRequest:output_type -> alertapi.AlertArray
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alertapi_alertapi_proto_init() }
func file_alertapi_alertapi_proto_init() {
	if File_alertapi_alertapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alertapi_alertapi_proto_rawDesc), len(file_alertapi_alertapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alertapi_alertapi_proto_goTypes,
		DependencyIndexes: file_alertapi_alertapi_proto_depIdxs,
		MessageInfos:      file_alertapi_alertapi_proto_msgTypes,
	}.Build()
	File_alertapi_alertapi_proto = out.File
	file_alertapi_alertapi_proto_goTypes = nil
	file_alertapi_alertapi_proto_depIdxs = nil
}
