name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Build all
      run: make build-all
      
    - name: Test
      run: go test -v ./...

    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v5.6
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }} 
      
    # - name: Archive Release
    #   uses: thedoctor0/zip-release@master
    #   with:
    #     type: 'zip'
    #     filename: 'symon_${{ steps.tag_version.outputs.new_tag }}.zip'
    #     exclusions: '*.git* *.go* *.mod *.sum /*internal/*'

    # - name: Upload Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: 'symon_${{ steps.tag_version.outputs.new_tag }}.zip'
    #     tag: ${{ steps.tag_version.outputs.new_tag }}
    #     name: Release ${{ steps.tag_version.outputs.new_tag }}
    #     commit: ${{ steps.vars.outputs.sha }}
    #     token: ${{ secrets.GITHUB_TOKEN }}  
